name: Publish Python 🐍 package to PyPI

on:
  push:
    branches:
      - pypi-deploy
    tags:
      - 'v*'

jobs:
  build-and-publish:
    name: Build and publish to PyPI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build package
        run: |
          python -m build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@v1.8.12
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
